name: lunr
description: A bit like Solr, but much smaller and not as bright (dart port of lunrjs.com)
version: 2.3.10
repository: https://github.com/sjhorn/lunr

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  collection: ^1.17.0
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  coverage: ^1.6.3

